name: Continuous Integration, Build and Deploy

#
# > Lint and Test all commits
# > Build and deploy tagged releases to Docker Hub
# > Build and deploy PR branches to GitHub Container Registry
#
# > Slack notifications are only sent for tagged release builds
#
# - Supported architectures -
#
# > AMD64     - AMD 64-bit x86 (Most platforms and the default architecture)
# > ARM64     - ARM 64-bit (Raspberry Pi 3 and later)
# > ARMv7     - ARM 32-bit (Raspberry Pi 2 Model B)
#

on:
  # schedule:
  #   - cron: "0 2 * * *" # everyday at 02:00 UTC
  push:
    paths-ignore:
      - '.*'
      - '**/.*'
      - project/tools/**
    #paths:
    # branches:
    #   - "**"
    tags:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Linting on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          cd project
          yarn install

      - name: Lint
        run: |
          cd project
          yarn nx run-many --target=lint --all

  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['14']
        os: [ubuntu-latest] #windows-latest, macOS-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: |
          cd project
          yarn install

      - name: Test
        run: |
          cd project
          yarn nx run-many --target=test --all

  build-deploy-docker-hub:
    name: Build and Deploy releases to Docker Hub
    if: ${{ contains(github.ref, 'master') && github.event == 'push tag' }}
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ github.repository }}/enjinex

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./project/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          # Always push as latest tag, Docker Hub builds the image tagged with version
          tags: ${{ steps.docker_meta.outputs.args.DOCKER_META_IMAGES }}:latest
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Slack
        uses: lazy-actions/slatify@v3.0.0
        with:
          type: ${{ job.status }}
          job_name: '${{ github.workflow }}'
          mention: 'channel'
          mention_if: 'failure'
          commit: true
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  build-deploy-github-cr:
    name: Build and Deploy PR branch to GitHub CR
    if: ${{ github.event_name == 'pull_request' }}
    needs: [lint, test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ghcr.io/${{ github.repository }}/enjinex

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./project
          file: ./project/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
